spring.application.name=whatsappdemo

# your twilio account sid, token and given twilio number
twilio.account_sid= twilio account sid 
twilio.auth_token= twilio auth token
twilio.whatsapp_number=whatsapp: twilio whatsapp number

server.port=9000